reference-ril: Fix -Wsometimes-uninitialized
hardware/ril/reference-ril/reference-ril.c:556:9: error:
variable 'atCommand' is used uninitialized whenever switch
default is taken [-Werror,-Wsometimes-uninitialized]
  556 |         default:
      |         ^~~~~~~
hardware/ril/reference-ril/reference-ril.c:559:21: note: uninitialized use occurs here
  559 |     at_send_command(atCommand, NULL);
      |                     ^~~~~~~~~
hardware/ril/reference-ril/reference-ril.c:522:20: note:
initialize the variable 'atCommand' to silence this warning
  522 |     char* atCommand;
      |                    ^
      |                     = NULL

Bug: 455664882
Test: build with clang-r584948
Change-Id: Id6f4890ab0d888f7db0701f4d570547df12c9385